language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  app: microservice-study-frontend
  apy_key:
    secure: NclxY6SFIMAQx/XxuiftY7wz5pqRGkKPKOOgp4oodFkP9Hz4qV8GXq6EcPkgG/KCalfGIHisywx3lMslryeybOu8wtXORN0avdKZ+1owmFDih2aky+f4/qcp2HkhHddb++lvhrHtk/6X7OdLVZLVrDiVYybJVM9VZ+tCI1ChxNdGNwzsBwEJZ/PSRA6xzMZvDl13UQgfwSkUy0Sw4DXZNpmI2+IsoV8WdDpL9Z2dWZNFMLHqraSQwTn24GARpp03UxatYrsXp3CaekaD0UhuURSyXFzKfLlUCdL7yVhZYtSG7MkA2H877w/Af0OPbi4Jvwq2Y+XLmfHkXtjW8PVmyKvYFDV9xy3CezqmYTCaEDeec9Dn3x56CN+xrWOw1t4Aah4y3fYuIsSho/l5sV3epIRMCmIAJYaATZTa33/zT5PWkxJ+nYWSou2rJ6qofNZj08YNNEnLj3ZZTvBMZ5L0RR86IfjYWL2L+F56Ww3Jrqzd1/RiRsd1LQf9ErC3yEKmg8vdGdKCAkkBoYYEtVdmnb0PFv8/IaNpxfuIe5yv2IvleETlDNfAN8iQG+0Lr97ll0b+B1DdH1jHTV5F18wfLEebE/zAnmMxL6Rxt4yMky+yw6KXR+LbgTcn7ccTBapzbyqu4tYcAN/Yu1zlF0/nLIln5MCZEWV5mnbRRPmSqWc=
