language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  api_key:
    secure: pYisBaKtTTAjXhvMvOPHa7LB/wFpigk4CRORN6fwUfpMy/Ux5aAljogW7rWIhyqK2SOS40F/ARupjlsSqEdbD+8QTwUWIIC/+0kYVWEhYpV0kMEYPsm3cVQV2p7b7uQJA4kceoezhJiOgRxs+RKSY61AT+LsP4S7VK5RSrvCtCMtNEijmQJLVkwHENlNW3Ng5CW3YeETOFJhsMfO5zlZBy1PkUuLbaENjHJkyB/vNywWaozntu7SRbQVOoXLrqBuB28ioZKYW6KrO7UpdcUmk+R8BCa5suUaCn++QUChYtmq6+3gkudO1f+q1FrpTvqE/cXEzXCIxjxM2jman5ZQjMRgUHz3N07v7dBmf5IBB3m/mvbZ+anzmMvzkTpLaoPFfD2AGHh42KCXAx9lQdXVrtFWMgaR/mPhF0k+h5sq9+U79kCQRVUQS86MO6bif/QexHwjzwMn8rFLFdtoPJohPM7ZdMMRo7xQS1Q5XUZ4pd+kwuv1LcMmYyV5lPHXv35kOFn0oHolkn0WsgS+TDO2JcpKXfAIyOLA998tP1BW0Bk6QBXlbAA8KKpCToXcQ0K/Rsw3RvlctTZ4H2LT6Own0wMQf6OmG9RXkt0bjLvN1PQqKkCnbtmawRgQNpQIW4h+d0db9BC8Z8qC4WwTj41OYdoaJxSwnIFNNMzt9czKmWM=
  app: microservice-study-frontend
  on:
    repo: lucasdornelles/MicroserviceStudyFrontend
