language: node_js
node_js:
  - 10.16.3
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - source heroku_deploy.sh
after_success: deployToHeroku $HEROKU_APP_NAME_LIVE
env:
  global:
    - HEROKU_APP_NAME_STAGE: microservice-study-frontend
    - HEROKU_APP_NAME_LIVE: microservice-study-frontend
