language: node_js
node_js:
  - 10.16.3
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - bash heroku_deploy.sh
env:
  global:
    - HEROKU_APP_NAME_LIVE: microservice-study-frontend
