language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  api_key:
    secure: JehE5BehMOQUj+gwtERsCbHxOkd/2w2/2H2wpOodr76LdiKN1CJX5Khk6/0csga2TIZiTbHh6HXtDi+50kQEWXoj5Ot2wj36lfz/H0u5a2/qmfRFWxZbYT3Ljx2tlZZeJ5hFkuHBFCZZFZ/ClCqJcufuCzlDcsUrzpndoqTEih2xu8jrHU7KFavaJAW1AdG6hA3ds5bbTIM8XwwmsthqSVQZ3ec5+IdzRlkmPife0B9tZVSIKjKIEZ1nzkiRSy2/sDxUsDvBwFP3wcZADOe58VijMm/e/Wo3h4MBYE2AN2qSsn2OBhaNO2YfptMZQPK1IYJAl+1yfP0KRawQakoUrv81qZafPwPxufnQDNNnaQ7Clol+URSL8CSPV7cgdrGmQdYxGGOdg/XT6/y+sPOW6+E79LKW20VMG85KfoPoHRKSjNO5/soDGShpBE5JYQbUJ3iXuHb6hyCy+CIUY6i3q9Zb2T/40JAVC9/n1mdlFk0lC1UYRidSUSqlroTsGGTKFDDcYHlNsLmka0gjhfG+RB6W27mc+EQ0i5gS5tixCn+eu7w5w6TkETFGMmmwLtwDyrHsZB7M6qZgTMj8pl6QfmuEgXa7Yhv+3pZvZe/+AtU8Ja210JN8KtINUmUzDqswMJYxQhOgrGWxOmbJX/O6bE30mem34nSbVm4cEebtwp8=
  app: microservice-study-frontend
  on:
    repo: lucasdornelles/MicroserviceStudyFrontend
