language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  app: microservice-study-frontend
  apy_key:
    secure: f2ECvo4C8x4OgQ6kBZJPYH80I0f+1q1xzK+cxOIriloIcJZRTx4IRZqiStxKrtFeSkfGHy8rYcu7lfhhjGVHxs8jfzr/9DEHJfPx7ZJ2zdVkioWNETPEk2BPddYaM/z913wTWPl8E0n2mRHz/CyVy5rAMDHiC7+EpZVece2AfDvfn9Lo/nc7Js2t1oYhGnX1QtB7o5/s7vWp6yedbSuFSIV5m+Yd0WGEiInY/OKJB0OtEWEi6FC+xF2Vc/Oia209wBYBHaYzZXwSyNgme1pehpT/k3B/MZJSHsyY3yecVFk4+fdwbNSVisYnDwJWnUbBdxqgDo6eoGPuqMgIlYl1s6iGeJDhi7do3nwNwWNchneqc/znh67UkrGU2zZ4/3CegZPosjQI8rPlRnjdFWseqcd3yBjTKkS7KbRTVP2PdxJtS4i+iPHcPTfbWy9+S+1xs30QSkTMb7QW5Vl3h9gkbranIH2ByHr0uxiInaY5pJ6ge55E2obiNosXit2yc3qAg/TydlecSfXMrxOrs1tkWymWqYkRk3oJlWpcwySecLiawxZzBzmlke7daDj8e58Zz8qLxjBqwahHpaP/jC0Wd4LeEFnIcs8pOQzKRbioEXy1TTEnXJFunjhpNzhCM4fB5cQdlNbl0AuXBbXjQF9GC+NJESy5HuBDtd3Djqs/mSs=
