language: node_js
node_js:
- 10.16.3
deploy:
  provider: heroku
  api_key:
    secure: nWkS8K9OIfDSVyp6s/L66ok0nNsNeVlA/psxzDeTyLXSTv1d7RTewT+1oSPzsEn2REY0Nh2MPwXNLGywtfhved9fauE20vUaTGQYMelL5LnejPQI9TBcHao2T3w/VZl+FAacmNPVnN1/uhgn69sPcQ71DPGzjqQRzpovOuYYCN6eT7BOk0nnYWLa0SElfFXIY77taHKVBjUlRakp+RJJsKNiKiZ3JkML017gTDlAotFkX7Dw+s5G5qab34vilOYpcIilgaxnPcEkuvenF+4XcTOUdoc2pN1Qp7eKYMecdMUxVt/ENBHusAG6PBwbvCIsVVrV6g+bSQJ7NtBz014Drtce/zNqRWVqTOMyjuh5bqYaOQ/WiI8uwo/2uBFUTVeErUC98F9NtesJmxrC91cCExKhVdRQqro2wAfiA8LdSTf0f4GyZT47+BkPL/zLhQP4l1BiV+UPSZt1RCEBiB7AAHvBlJIFrMYogNtGKd6jLLXjbzTAPycwsswH891DCAdENqWVeaeHshamrBVcIrHsDfRat786VK2MM39filMS+VlEmI7Dysu+IG5sxdFedLInJhsNZYw54FEBQQyPazFB0XfFlQuVX9P+KwpxcDuUeVLj2OBbKMont5ttOOdJuKrotjqe8RHDWxT5QVk1k9jQC4G1VldgkOXO1Q4kT0u+BfM=
  app: microservice-study-frontend
  on:
    repo: lucasdornelles/MicroserviceStudyFrontend
